import AppTemplate from '@/components/templates/AppTemplate';
import Layout from '@/components/templates/Layout';
import { APP_NAME } from '@/constant';
import { privateRouteAdmin } from '@/lib/withprivateRouteAdmin';
import { Box, Flex, Text } from '@chakra-ui/layout';
import {
  createStandaloneToast,
  Stat,
  StatLabel,
  StatNumber,
} from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { ReactNode, useEffect, useState } from 'react';
import { BsFillDatabaseFill } from 'react-icons/bs';
import { ImBooks } from 'react-icons/im';
import { GiBookshelf } from 'react-icons/gi';
import { ApiGetCountBuku } from '@/api/buku';

const ManajemenkatalogAdmin: NextPage = () => {
  const router = useRouter();
  const [dataCountBuku, setDataCountBuku] = useState({
    totalBukuKatalog: 0,
    totalBukuPerpus: 0,
  });
  const { toast } = createStandaloneToast();

  const gotoBukuKatalog = () => {
    router.push('/admin/manajemen-katalog/katalog');
  };

  const gotoBukuPerpus = () => {
    router.push('/admin/manajemen-katalog/list-buku-perpus');
  };

  const getCountBuku = async () => {
    const res = await ApiGetCountBuku();
    if (res.status === 200) {
      setDataCountBuku(res.data.data);
    } else {
      toast({
        status: 'error',
        duration: 5000,
        title: 'Error',
        description: res.data.message,
        position: 'bottom-right',
      });
    }
  };

  useEffect(() => {
    getCountBuku();
  }, []);

  return (
    <Layout>
      <Head>
        <title>{APP_NAME} | Admin | Manajemen Katalog | Buku</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppTemplate>
        <Box p='4' h='full'>
          <Text fontWeight='700' color='gray.700' fontSize='2xl'>
            Manajemen Buku
          </Text>
          <Flex
            h='80vh'
            justifyContent='center'
            alignItems='center'
            my='4'
            gap='20px'
            flexDirection='column'
          >
            <Box w='40%'>
              <Box onClick={gotoBukuKatalog}>
                <StatsCard
                  title='Buku Katalog'
                  stat={dataCountBuku.totalBukuKatalog}
                  icon={<ImBooks size={'5em'} />}
                />
              </Box>
            </Box>
            <Box w='40%'>
              <Box onClick={gotoBukuPerpus}>
                <StatsCard
                  title='Buku Perpus'
                  stat={dataCountBuku.totalBukuPerpus}
                  icon={<GiBookshelf size={'5em'} />}
                />
              </Box>
            </Box>
          </Flex>
        </Box>
      </AppTemplate>
    </Layout>
  );
};

// export default privateRouteAdmin(ManajemenkatalogAdmin);
export default ManajemenkatalogAdmin;

interface StatsCardProps {
  title: string;
  stat: number;
  icon: ReactNode;
}
function StatsCard(props: StatsCardProps) {
  const { title, stat, icon } = props;
  return (
    <Stat
      _hover={{ cursor: 'pointer' }}
      px={{ base: 2, md: 4 }}
      py={'5'}
      shadow={'xl'}
      border={'1px solid'}
      borderColor={'gray.800'}
      rounded={'lg'}
    >
      <Flex justifyContent={'space-between'}>
        <Box pl={{ base: 2, md: 4 }}>
          <StatLabel fontWeight={'medium'} fontSize='4xl'>
            {title}
          </StatLabel>
          <StatNumber fontSize={'2xl'} fontWeight={'medium'}>
            {stat}
          </StatNumber>
        </Box>
        <Box my={'auto'} color={'gray.800'} alignContent={'center'}>
          {icon}
        </Box>
      </Flex>
    </Stat>
  );
}
