import AppTemplateProdi from '@/components/templates/AppTemplateProdi';
import LayoutProdi from '@/components/templates/LayoutProdi';
import { APP_NAME } from '@/constant';
import { getColorStatus } from '@/utils/colors';
import { Button } from '@chakra-ui/button';
import { Box, Flex, Text, VStack } from '@chakra-ui/layout';
import moment from 'moment';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useMemo, useState } from 'react';
import { BiArrowBack } from 'react-icons/bi';

// interface IReduxStateWorkspace {
//   user?: IUser;
// }

interface IDataRow {
  no: number;
  diAjuakanPada: string;
  prodi: string;
  judulBuku: string;
  jumlah: number;
  status: string;
  aksi: string;
}

const DetailPengajuanProdi: NextPage = () => {
  const router = useRouter();
  const [dataPengguna, setDataPengguna] = useState<IDataRow[]>([
    {
      no: 1,
      judulBuku: 'Judul buku',
      prodi: 'Teknik Informatika',
      jumlah: 10,
      status: 'diproses',
      diAjuakanPada: moment().format('LLLL'),
      aksi: new Date().getTime().toString(),
    },
    {
      no: 2,
      judulBuku: 'Judul buku',
      prodi: 'Teknik Informatika',
      jumlah: 10,
      status: 'diterima',
      diAjuakanPada: moment().format('LLLL'),
      aksi: new Date().getTime().toString(),
    },
    {
      no: 3,
      judulBuku: 'Judul buku',
      prodi: 'Teknik Informatika',
      jumlah: 10,
      status: 'selesai',
      diAjuakanPada: moment().format('LLLL'),
      aksi: new Date().getTime().toString(),
    },
    {
      no: 4,
      judulBuku: 'Judul buku',
      prodi: 'Teknik Informatika',
      jumlah: 10,
      status: 'gagal',
      diAjuakanPada: moment().format('LLLL'),
      aksi: new Date().getTime().toString(),
    },
    {
      no: 5,
      judulBuku: 'Judul buku',
      prodi: 'Teknik Informatika',
      jumlah: 10,
      status: 'ditolak',
      diAjuakanPada: moment().format('LLLL'),
      aksi: new Date().getTime().toString(),
    },
  ]);

  const columns = useMemo(
    () => [
      {
        Header: 'No',
        accessor: 'no',
      },
      {
        Header: 'Diajukan Pada',
        accessor: 'diAjuakanPada',
      },
      {
        Header: 'Program Studi',
        accessor: 'prodi',
      },
      {
        Header: 'Judul Buku',
        accessor: 'judulBuku',
      },
      {
        Header: 'Jumlah',
        accessor: 'jumlah',
      },
      {
        Header: 'Status',
        accessor: 'status',
      },
      {
        Header: 'Aksi',
        accessor: 'aksi',
      },
    ],
    []
  );

  // const { user } = useSelector<ICombinedState, IReduxStateWorkspace>(
  //   (state) => {
  //     return {
  //       user: state.user.user,
  //     };
  //   }
  // );

  //   Aksi
  // Status

  const getData = () => {};

  return (
    <LayoutProdi showOnlyInfoUser>
      <Head>
        <title>{APP_NAME} | Prodi | Pengajuan</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppTemplateProdi>
        <Box w='full'>
          <Link href='/prodi/manajemen-pengajuan'>
            <Button leftIcon={<BiArrowBack />} size='md' colorScheme='blue'>
              Kembali
            </Button>
          </Link>
          <Box my='5'>
            <Text fontSize='xl' fontWeight='700'>
              Detail Pengajuan Buku
            </Text>
            <Box my='5'>
              <VStack spacing={3} w='full' alignItems='flex-start'>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    w='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='2'
                  >
                    Id Pengajuan Buku
                  </Flex>
                  <Text>: {new Date().getTime()}</Text>
                </Flex>

                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    w='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='2'
                  >
                    Judul Buku
                  </Flex>
                  <Text>: Judul Buku</Text>
                </Flex>

                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    w='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='2'
                  >
                    Jumlah Buku
                  </Flex>
                  <Text>: 9</Text>
                </Flex>

                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    w='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='2'
                  >
                    Informasi Tambahan
                  </Flex>
                  <Text maxW='500px'>
                    : Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Maxime molestiae accusamus harum laborum libero fuga! Hic
                    qui consequuntur quaerat voluptatum Lorem ipsum dolor sit
                    amet consectetur adipisicing elit. Maxime molestiae
                    accusamus harum laborum libero fuga! Hic qui consequuntur
                    quaerat voluptatumLorem ipsum dolor sit amet consectetur
                    adipisicing elit. Maxime molestiae accusamus harum laborum
                    libero fuga! Hic qui consequuntur quaerat voluptatum?
                  </Text>
                </Flex>

                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    w='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='2'
                  >
                    Status
                  </Flex>
                  <Flex
                    padding='1'
                    borderRadius='10px'
                    alignItems='center'
                    bgColor={getColorStatus('diterima')}
                    justifyContent='center'
                  >
                    <Text color='white' fontWeight='700'>
                      diterima
                    </Text>
                  </Flex>
                </Flex>

                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    w='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='2'
                  >
                    Informasi Admin
                  </Flex>
                  <Text maxW='500px'>
                    : Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Maxime molestiae accusamus harum laborum libero fuga! Hic
                    qui consequuntur quaerat voluptatum Lorem ipsum dolor sit
                    amet consectetur adipisicing elit. Maxime molestiae
                    accusamus harum laborum libero fuga! Hic qui consequuntur
                    quaerat voluptatumLorem ipsum dolor sit amet consectetur
                    adipisicing elit. Maxime molestiae accusamus harum laborum
                    libero fuga! Hic qui consequuntur quaerat voluptatum?
                  </Text>
                </Flex>
              </VStack>
            </Box>
          </Box>
        </Box>
      </AppTemplateProdi>
    </LayoutProdi>
  );
};

export default DetailPengajuanProdi;
// export default privateRouteAdmin(DetailPengajuanProdi);
