import { ApiGetDetailPengajuanBuku } from '@/api/pengajuanBuku';
import AppTemplateProdi from '@/components/templates/AppTemplateProdi';
import LayoutProdi from '@/components/templates/LayoutProdi';
import { APP_NAME } from '@/constant';
import { IDataBuku, IPengajuanBuku } from '@/interface';
import { getColorStatus } from '@/utils/colors';
import { Button } from '@chakra-ui/button';
import { Box, Flex, Text, VStack } from '@chakra-ui/layout';
import { createStandaloneToast } from '@chakra-ui/toast';
import moment from 'moment';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { BiArrowBack } from 'react-icons/bi';
import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
} from '@chakra-ui/react'

// interface IReduxStateWorkspace {
//   user?: IUser;
// }

interface IDataRow {
  no: number;
  diAjuakanPada: string;
  prodi: string;
  judulBuku: string;
  jumlah: number;
  status: string;
  aksi: string;
}

const DetailPengajuanProdi: NextPage = () => {
  const router = useRouter();
  const { toast } = createStandaloneToast();
  const [data, setData] = useState<IPengajuanBuku>();

  const getData = async (id: string) => {
    const res = await ApiGetDetailPengajuanBuku(id);
    if (res.status === 200) {
      setData({
        ...res.data.data,
        // buku: res.data.data.buku._id.judul,
        jumlah: res.data.data.buku.length + res.data.data.bukuLink.length,
      });
    } else {
      toast({
        status: 'error',
        duration: 5000,
        title: 'Error',
        description: res.data.message,
        position: 'bottom-right',
      });
    }
  };

  const getJumlahTotalBuku = (status?: string) => {
    let total = 0;
    if (status) {
      if (status === 'diproses') {
        data?.buku.filter((dt: any) => dt.status === 'diproses').map((bk: any) => (total += bk.jumlah));
        return total;
      } else if (status === 'diterima') {
        data?.buku.filter((dt: any) => dt.status === 'diterima').map((bk: any) => (total += bk.jumlah));
        return total;
      } else if (status === 'selesai') {
        data?.buku.filter((dt: any) => dt.status === 'selesai').map((bk: any) => (total += bk.jumlah));
        return total;
      } else if (status === 'gagal') {
        data?.buku.filter((dt: any) => dt.status === 'gagal').map((bk: any) => (total += bk.jumlah));
        return total;
      } else if (status === 'ditolak') {
        data?.buku.filter((dt: any) => dt.status === 'ditolak').map((bk: any) => (total += bk.jumlah));
        return total;
      }
    }
    data?.buku.map((bk: any) => (total += bk.jumlah));

    return total;
  };

  useEffect(() => {
    const id: any = router.query.id;
    if (id) {
      getData(id);
    }
  }, [router.query]);

  return (
    <LayoutProdi showOnlyInfoUser>
      <Head>
        <title>{APP_NAME} | Prodi | Pengajuan</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppTemplateProdi>
        <Box w='full'>
          <Link href='/prodi/manajemen-pengajuan'>
            <Button leftIcon={<BiArrowBack />} size='md' colorScheme='blue'>
              Kembali
            </Button>
          </Link>
          <Box my='5'>
            <Text fontSize='xl' fontWeight='700'>
              Detail Pengajuan Buku
            </Text>
            <Box my='5'>
              <VStack spacing={3} w='full' alignItems='flex-start'>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Id Pengajuan Buku
                  </Flex>
                  <Text>: {data?._id}</Text>
                </Flex>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Tanggal Pengajuan
                  </Flex>
                  <Text>: {moment(data?.createdAt).format('LLL')}</Text>
                </Flex>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Status
                  </Flex>
                  <Flex
                    padding='1'
                    borderRadius='10px'
                    alignItems='center'
                    bgColor={getColorStatus(data?.status ?? '')}
                    justifyContent='center'
                  >
                    <Text color='black' fontWeight='700'>
                      {data?.status}
                    </Text>
                  </Flex>
                </Flex>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Jumlah Buku
                  </Flex>
                  <Text>: {data?.jumlah}</Text>
                </Flex>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Jumlah Total Buku
                  </Flex>
                  <Text>: {getJumlahTotalBuku()}</Text>
                </Flex>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Jumlah Total Buku Diproses
                  </Flex>
                  <Text>: {getJumlahTotalBuku('diproses')}</Text>
                </Flex>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Jumlah Total Buku Diterima
                  </Flex>
                  <Text>: {getJumlahTotalBuku('diterima')}</Text>
                </Flex>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Jumlah Total Buku Ditolak
                  </Flex>
                  <Text>: {getJumlahTotalBuku('ditolak')}</Text>
                </Flex>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Jumlah Total Buku Selesai
                  </Flex>
                  <Text>: {getJumlahTotalBuku('selesai')}</Text>
                </Flex>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Pesan Ke Admin
                  </Flex>
                  <Text maxW='500px'>: {data?.pesanDosen}</Text>
                </Flex>
                <Flex alignItems='center' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Pesan Dari Admin
                  </Flex>
                  <Text maxW='500px'>: {data?.pesanAdmin}</Text>
                </Flex>
                <Flex alignItems='flex-start' gap='15px'>
                  <Flex
                    borderColor='blue'
                    minW='300px'
                    borderWidth='1px'
                    alignItems='center'
                    justifyContent='center'
                    padding='1'
                  >
                    Informasi Buku :
                  </Flex>
                </Flex>
                {data &&
                  <TableContainer>
                    <Table size='sm'>
                      <Thead>
                        <Tr>
                          <Th>No</Th>
                          <Th>Judul Buku</Th>
                          <Th>Katalog</Th>
                          <Th textAlign="center">Jumlah</Th>
                          <Th>Keterangan</Th>
                        </Tr>
                      </Thead>
                      <Tbody>
                        {data?.buku.map((buku: any, i: number) => (
                          <Tr key={i}>
                            <Td>{i + 1}</Td>
                            <Td>{buku._id?.judul}</Td>
                            <Td textAlign="center">{buku?._id?.katalog?.name ?? "-"}</Td>
                            <Td textAlign="center">{buku?.jumlah}</Td>
                            <Td>
                              <Flex
                                padding='1'
                                borderRadius='10px'
                                alignItems='center'
                                bgColor={getColorStatus(buku.status ?? '')}
                                justifyContent='center'
                              >
                                <Text color='black' fontWeight='700'>
                                  {buku?.status}
                                </Text>
                              </Flex>

                            </Td>
                          </Tr>


                        ))}
                      </Tbody>
                    </Table>
                  </TableContainer>

                }
              </VStack>
            </Box>
          </Box>
        </Box>
      </AppTemplateProdi>
    </LayoutProdi>
  );
};

export default DetailPengajuanProdi;
// export default privateRouteAdmin(DetailPengajuanProdi);
