import AppTemplate from '@/components/templates/AppTemplate';
import Layout from '@/components/templates/Layout';
import { APP_NAME } from '@/constant';
import {
  Box,
  Flex,
  Heading,
  HStack,
  SimpleGrid,
  Text,
} from '@chakra-ui/layout';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useSelector } from 'react-redux';
import { privateRouteAdmin } from '@/lib/withprivateRouteAdmin';
import { BiSolidBarChartAlt2 } from 'react-icons/bi';

// interface IReduxStateWorkspace {
//   user?: IUser;
// }

const BerandaAdmin: NextPage = () => {
  const router = useRouter();
  // const { user } = useSelector<ICombinedState, IReduxStateWorkspace>(
  //   (state) => {
  //     return {
  //       user: state.user.user,
  //     };
  //   }
  // );

  return (
    <Layout>
      <Head>
        <title>{APP_NAME} | Admin | Beranda</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppTemplate>
        <Box>
          <Text fontSize='2xl'>Selamat Datang</Text>
          <Text>FULLNAME, Admin</Text>
          <Box my='8'>
            <Heading as='h3' fontWeight='700'>
              Data Statistik
            </Heading>
            <Box my='4'>
              <SimpleGrid spacing={3} columns={[2]}>
                <ItemStatistik
                  bgColor='green.100'
                  title='Daftar Buku'
                  count={100}
                />
                <ItemStatistik
                  bgColor='orange.100'
                  title='Daftar Katalog'
                  count={100}
                />
                <ItemStatistik
                  bgColor='yellow.100'
                  title='Permintaan Pengajuan Buku'
                  count={100}
                />
                <ItemStatistik
                  bgColor='purple.100'
                  title='Permintaan Pengajuan Buku Diterima'
                  count={100}
                />
                <ItemStatistik
                  bgColor='red.100'
                  title='Permintaan Pengajuan Buku Diterima'
                  count={100}
                />
              </SimpleGrid>
            </Box>
          </Box>
        </Box>
      </AppTemplate>
    </Layout>
  );
};

export default BerandaAdmin;
// export default privateRouteAdmin(BerandaAdmin);

interface IItemStatistik {
  bgColor: string;
  title: string;
  count: any;
}

const ItemStatistik: React.FC<IItemStatistik> = ({ bgColor, title, count }) => {
  return (
    <Flex
      w='full'
      // justifyContent='space-between'
      padding='4'
      h='180px'
      alignItems='center'
      gap='10px'
      borderRadius='8px'
      bgColor={bgColor}
    >
      <BiSolidBarChartAlt2 size={100} />
      <Flex flexDirection='column' h='100px' justifyContent='space-between'>
        <Text fontSize='2xl'>{title}</Text>
        <Text fontSize='2xl' fontWeight='800'>
          {count}
        </Text>
      </Flex>
    </Flex>
  );
};
