import Layout from '@/components/templates/Layout';
import { APP_NAME, LOCAL_USER_TYPE } from '@/constant';
import { setLocal } from '@/lib/LocalStorage/localStorage';
import type { NextPage } from 'next';
import Head from 'next/head';
import Router from 'next/router';
import { useEffect } from 'react';

// interface IReduxStateWorkspace {
//   user?: IUser;
// }

const LogoutAdmin: NextPage = () => {
  useEffect(() => {
    setLocal(LOCAL_USER_TYPE, '');
    Router.replace('/login');
  });

  return (
    <Layout>
      <Head>
        <title>{APP_NAME} | Admin | Logout</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </Layout>
  );
};

export default LogoutAdmin;
